# Generated by Django 5.1.7 on 2025-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_stamp',
            field=models.CharField(choices=[('original', 'Original Stamp'), ('cit', 'CIT Stamp'), ('both', 'Both Stamps'), ('none', 'No Stamp')], default='none', max_length=20),
        ),
    ]
